version: '2'

services:
  app:
    image: 'chatbox:latest'
    build:
      context: .
    container_name: chatbox
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chatbox
      - SPRING_DATASOURCE_USERNAME=chatboxadmin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8901:8901"
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=chatbox
      - POSTGRES_USER=chatboxadmin
      - POSTGRES_PASSWORD=password
#      - POSTGRES_HOST_AUTH_METHOD=true